### ISSUE TITLE
Option to output json?

### ISSUE THREAD

**Issue by st0le** [demoray/azure-storage-cli#86]
At the moment, the tool outputs a pseudo-json like format. This blocks using azs with other tools.

**Comment by demoray** [comment]
I would love to do so.

Unfortunately, most of the APIs from the azure SDK for Rust do not provide a serializable output in the response.  As this CLI is a thin wrapper around the SDK, it would be significantly more work to enable it than I have at the moment.

I've added #116 to at least identify the commands that _do_ output in json.
